### ISSUE TITLE
Go Conference 2019 in Fukuoka

### ISSUE THREAD

**Issue by linyows** [fukuokago/event#10]
福岡でGoコンやるのだ！東京とずらしてSummer?

**Comment by monochromegane** [comment]
大注目Issueじゃん

**Comment by linyows** [comment]
TODO

- [x] 日程調整
- [x] 会場選定
- [ ] スポンサー枠検討
- [ ] スポンサー募集
- [ ] キーノートどうするか
- [ ] 募集サイト

- - -

参加無料にしたいからスポンサー会場提供の方向で考えたい

**Comment by monochromegane** [comment]
とりあえず GoCon主催とは飲み会の場レベルでやりましょうの話なので，やるなら正式に筋を通す必要ありです

**Comment by linyows** [comment]
一番大事なやつですね

**Comment by monochromegane** [comment]
先にOKもらってた方が色々進めやすいでしょうから， tenntennさん経由で打診してみます．

**Comment by linyows** [comment]
yo

**Comment by linyows** [comment]
よろます〜

**Comment by monochromegane** [comment]
FGNのリニューアルが来年の5月なので，イベントスペースが広いところができればいいな．
調整次第で無料でできるようなことを言ってた気もするのでメモ
https://growth-next.com/fgn2/

**Comment by linyows** [comment]
FGN良さそう！規模感としては100〜200。レベル感分ける目的で2トラックもあり。

**Comment by monochromegane** [comment]
一旦 tenntenn さんに開催に関する福岡側の準備は整っている旨と開催可否を打診

**Comment by monochromegane** [comment]
GoCon運営側はぜひとのこと，進めていきましょう！！
また，スピーカーやスポンサーなども色々相談できるとのこと，ありがたや〜

**Comment by linyows** [comment]
わーい ㊗️

**Comment by linyows** [comment]
福岡市の方やFGN事務局とお話ししやすいように企画書的（背景、目的云々）なものを準備する

**Comment by linyows** [comment]
打ち合わせの調整はMr. Kにお願いする

**Comment by monochromegane** [comment]
Mr.K調整します~

**Comment by linyows** [comment]
キックオフ的なものはやっているので閉じ
