### ISSUE TITLE
GoCon2019 タイムテーブルを決める

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#15]
## 期日

1月中

## 成果物

タイムテーブル

- [x] 開始，終了
- [x] トークの種別と時間（ロングとショート，スポンサー枠，LTなど）
- [x] 2トラック制でなるべく多くトークがあるような時間割
- [x] 休憩を含める
- [x] 質疑応答を含めるかを検討
- [x] 懇親会を含めるかを検討

**Comment by monochromegane** [comment]
なるべくたくさんの登壇者に話してもらう機会があるといい（東京から来る人も増える）のでキーノートはない方向で考えている

**Comment by monochromegane** [comment]
スポンサーセッションは，2トラック制ってあんまり聞かないなあ．
会場繋げるかどうかで構成が変わって来そうだ

**Comment by monochromegane** [comment]
タイムテーブルの案．Long(40min), Short(20min), Suponsor(20min)
ref: https://docs.google.com/spreadsheets/d/1qdJNlvYoo7RjOf_hEADjLrvAqeWpfrWCMQVjLt6EFjU/edit#gid=0

minutes | title | start | end
-- | -- | -- | --
0:30 | Open | 9:30 | 10:00
0:10 | Opening talk | 10:00 | 10:10
0:40 | Long talk | 10:10 | 10:50
0:20 | Suponsor talk | 10:50 | 11:10
0:20 | Suponsor talk | 11:10 | 11:30
0:20 | Short talk | 11:30 | 11:50
1:30 | Lunch break | 11:50 | 13:20
0:20 | Suponsor talk | 13:20 | 13:40
0:20 | Short talk | 13:40 | 14:00
0:20 | Short talk | 14:00 | 14:20
0:40 | Long talk | 14:20 | 15:00
0:10 | Break | 15:00 | 15:10
0:20 | Short talk | 15:10 | 15:30
0:20 | Short talk | 15:30 | 15:50
0:40 | Long talk | 15:50 | 16:30
0:20 | Break | 16:30 | 16:50
0:20 | Suponsor talk | 16:50 | 17:10
0:20 | Short talk | 17:10 | 17:30
0:20 | Short talk | 17:30 | 17:50
0:10 | Close | 17:50 | 18:00

---

Talk type    | Count(x2)
-- |  --
Long talk |  6
Short talk | 14
Suponsor talk | 8

スポンサートークは会場繋いで 4つにする？

**Comment by monochromegane** [comment]
```
monochromegane [3:20 PM]
ワイワイ
2トラック完全分離だと音声とかがかなり楽ではあるのでスポンサーセッションも会場ごとって言ってしまった方がいいですかね

linyows [3:22 PM]
分けていいんじゃないすかねー

monochromegane [3:22 PM]
そうすると楽だなあ．数も確保できるし．ではその方向で
```

**Comment by monochromegane** [comment]
質疑応答は上記枠に含める

**Comment by monochromegane** [comment]
懇親会のタイムテーブルはまた懇親会Issueでやる

**Comment by linyows** [comment]
あざます！！！！！あまり変更不要そうな気がします。スポンサーセッションといえど、技術的にみんなが聞きたいセッションにしてもらえれば集客できると思いますので、少なくする必要はない気がしました。どっかのshort talk枠にに学生用LTを突っ込んでも良さそうですね！

**Comment by linyows** [comment]
15時あたりから、軽くお酒や軽食を出し始めるとか（徐々にFukuoka.goっぽく）

**Comment by monochromegane** [comment]
なるほど学生枠!
Short(20min)を学生用LT(10min x2)とかに分割すれば良さそう！
では大枠はこんな感じで，細かくトーク枠が決まれば，40 - 20 - 10 の枠で交換していきます〜

**Comment by linyows** [comment]
わーい

**Comment by monochromegane** [comment]
ご飯系，会場側とうまく連携して Fukuoka.go 感出したいですぞ！

**Comment by monochromegane** [comment]
一旦仮のタイムテーブルできたので閉じます．
懸念事項は一般懇親会をどうするかですが，それは https://github.com/fukuokago/event/issues/22 のIssueで進めます．
