### ISSUE TITLE
スポンサー内容を決める

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#16]
## 期日

2月〜3月中

## 成果物

- [x] スポンサー種別
- [x] スポンサー候補の選定
- [x] スポンサーのメリット（トークしてもらう？）

実際のスポンサーとの折衝は個別Issueとする

## 参考情報

```
## スポンサー
金銭ではなく、必要なものをお願いする形式でスポンサーを募ります。

- アルコール
- ソフトドリンク
- コーヒー
- 軽食
- 打ち上げ（飲食店タイアップ？）
- ビデオ配信
```

**Comment by linyows** [comment]
スポンサーセッションは8枠なので、30万円相当で必要なものをグループ分けして、8企業を募る。スポンサーセッションがつまんなくても困るので、Goにそれなりに関連している企業限定となる。

**Comment by linyows** [comment]
こんなもんかなあ

1. アルコール
1. コーヒー含むソフトドリンク
1. 軽食1
1. 軽食2
1. T-Shirts
1. ステッカー&パンフレット
1. 機材&ビデオ&写真
1. スタッフ打ち上げ

**Comment by linyows** [comment]
別枠でセッションなしのScholarshipsスポンサー

1. 学生の旅費と宿泊費

協力企業として

1. 前日にオフィス解放

**Comment by monochromegane** [comment]
fmfm! `6. ステッカー&パンフレット` とかは必要かなあなど思いながら，例えば，どれかを分割して，30万はでかいなあと思っているところ向けに10~15万のプランを作るとどうでしょう（ゴールド，シルバースポンサー的な）

**Comment by linyows** [comment]
確かに間口を広げるのは必要ですね！

**Comment by linyows** [comment]
Google Slideで作り始めた（大谷さんが叩きをつくる）

**Comment by yuji-otani** [comment]
スポンサープランの叩きを作成。
https://docs.google.com/spreadsheets/d/1elxTSIpHQGHLXTxyXnkSbvD6_QXorpoySeXA2KQHo7k/edit#gid=673467895

**Comment by linyows** [comment]
物品提供自体に露出ができるもの

- エコバッグ
- ステッカー
- バックパネル
- 水
- T-Shirts

露出がないもの

- ビールサーバ
- コーヒー
- 軽食
- 打ち上げ

**Comment by linyows** [comment]
打ち上げは金銭をもらわないと厳しいな

**Comment by linyows** [comment]
露出がないものはスケジュールにスポンサー紹介を入れる

**Comment by monochromegane** [comment]
東京GoConは懇親会スポンサーとしてオードブルとビールを準備してもらって，確か，その懇親会でのスポンサートークみたいな感じでやってましたね．
今回は必ず2trackなんで全員が見てくれるという意味だとそこを狙ってやってくれる人はいそう．

懇親会どこでやるのかにもよる（会場代）

**Comment by monochromegane** [comment]
ちょっとわからなくなってるんですが，露出とスポンサートーク枠が別ってなってきました？

**Comment by linyows** [comment]
もちろん、セッションは露出ですが、提供する物品に平等感を考えていました

**Comment by monochromegane** [comment]
なるほど...確かにそれは必要だと思えます．
スポンサーの特典は基本はスポンサーセッションへの登壇権利として平等にして，かかるコストだけで判断してもらった方がわかりやすそうだと思えました．（基本はスポンサーの名前は入れない）
スポンサー名称を入れたい奴はオプションでお金とか？

**Comment by linyows** [comment]
めでたいことに、8つの企業にスポンサーしてもらうことになりました https://fukuoka.gocon.jp/ja/sponsors/
