### ISSUE TITLE
CfPの告知を行う

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#17]
## 期日

4月中

## 成果物

- [x] 4/1にCfPページ公開（Google Form?，1月に決まったタイムテーブルを元に発表者枠とトーク種別を指定）
- [x] 4月いっぱいCfP受付

**Comment by monochromegane** [comment]
https://www.papercall.io/gocon-jp-2019-fukuoka でPaperCallに場所を作ってもらった〜

**Comment by monochromegane** [comment]
PaperCallを触ってみたが，募集に必要な項目の入力欄は変更できなさそうじゃった

**Comment by linyows** [comment]
そうすねー

**Comment by monochromegane** [comment]
ほえー
とりあえずLTは最初からは募集しないのでトークタイプからLTを外すのとデフォルトのtagにGopherConの時と同じ `go,golang` を追加しておきます

**Comment by monochromegane** [comment]
あとは イベント説明とCfP説明かな
https://www.papercall.io/gophercon-2019 が参考になるが，完全にパクるのもあれだな...
イベントページの英語化が済んだら持ってこようかな

**Comment by monochromegane** [comment]
CfP説明にスケジュールとトークタイプを追加．

```
# Schedule

- 15 March 2019. CFP opens.
- 30 April 2019, CFP closes.
- Middle May 2019, authors notified and schedule published.
- 13 July 2019, Go Conference'19 in Fukuoka, Japan.

# Talk types

- Keynote style presentations; 20 minute time limit, two tracks, questions at the presenter’s discretion.
- Tutorial style presentations; 40 minute time limit, two tracks, questions at the presenter’s discretion.
```

**Comment by monochromegane** [comment]
CFPページの更新が済んだのでReady to publish

- https://www.papercall.io/gocon-jp-2019-fukuoka
- https://www.papercall.io/cfps/1911/submissions/new

気になるところないかみなさんちらっと見てもらえると〜
（場所についてはまだ確定情報出せないらしく（何でやねん！）fukuoka.gocon.jpへのリンクを見てもらう感じです）

**Comment by linyows** [comment]
あざます！全体的に良さそうです！

~~ElevPitchとdescとnoteっていろいろあってわからんってなると困るから、サイトに日本語で説明入れておくかなーって思ったのと~~ 済 場所はいつ頃に公開できるってあるといいかなと思いました。

**Comment by monochromegane** [comment]
場所の公開時期はまだわからないので一旦保留

**Comment by monochromegane** [comment]
打ち合わせでアーリーフィードバックについて触れておいた方が良いとのことだったので以下をCFP descriptionに追加

```
### Advice for authors
You can fix your submission until the deadline after submitting. We recommend submitting early to receive early feedback from reviewers.
```

**Comment by linyows** [comment]
告知したので閉じる
