### ISSUE TITLE
イベント申し込み管理

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#19]
## 期日

5/13-5/31

## 成果物

- [ ] タイムテーブルの最新化
- [ ] 募集ページ（Connpass?)の公開
- [ ] 抽選

## メモ

人数については5/31のFGNリニューアルまでには絶対確定できるはず

**Comment by linyows** [comment]
枠としてはこんな感じかな

- 早期申込枠 15名
- 一般申込抽選枠 50名
- 遠方枠 5名
- プロポーザル枠 15名
- 女性／ジェンダーマイノリティ枠 15名
- スタッフ枠（前日16時からと当日）打ち上げ参加できます 3名
