### ISSUE TITLE
運営スタッフの募集

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#20]
## 期日

3月

## 成果物

- [ ] 運営スタッフの仕事を決める
- [ ] 募集（まずはペパボ，不足するならConnpassのイベントページで当日枠募集？）

## メモ

当日スタッフのやってほしいこと

- 受付
- 会場スタッフ
- 司会？
- 設営準備
- 撤収

**Comment by linyows** [comment]
受付と飲食と司会のチームに分かれて、各調整して交代する。手が空いてれば適当に登壇聞いたりするイメージ。

- [ ] 受付/会場チーム 4名
- [ ] 司会/会場チーム 4名
- [ ] 飲食管理チーム 4名
- [ ] 設営/撤収 全員
- [ ] SNS実況チーム 2名

@linyows と @monochromegane のどちらかは必ず手を空いた状態にしておく

**Comment by linyows** [comment]
当然スタッフはアルコール飲めない（打ち上げでヨロ）

**Comment by linyows** [comment]
成年バッジ、未成年バッジが必要そう

**Comment by monochromegane** [comment]
Twitterの実況スタッフとか考えてみたんですけど，サクラっぽいかなあ〜

**Comment by monochromegane** [comment]
人選は必要そうだけど...

**Comment by linyows** [comment]
実況いいですね、参加できてない人が嬉しい気がする

**Comment by linyows** [comment]
notionに段取り書いて共有
