### ISSUE TITLE
一般懇親会の検討

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#22]
## 期日

7/13

せっかくなので交流してGo仲間を増やしたりコラボや議論が生まれてほしい．
一般の参加者がGoConの後にそのまま飲食できる場を検討する．

## 成果物

- [ ] FGNが使えるか打診
- [ ] スポンサーでオードブルや飲み物提供ができるところを検討
- [ ] 会場が使えないなら有料の懇親会にするか検討
- [ ] その場合，会費の徴収方法の検討

## メモ

- LTなどできるとぼっちの人も寂しくない

**Comment by linyows** [comment]
イベントの延長で懇親会を1時間取ることが決まっているのでclose
