### ISSUE TITLE
運営スタッフ&発表者の打ち上げ（懇親会の二次会）

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#23]
## 期日

7/13

ここから生まれるコラボレーション．あとは単純に打ち上げたい

## 成果物

- [ ] 参加人数の見積もり
- [ ] お店の予約

**Comment by linyows** [comment]
お店決めないとなあー、人数は登壇者28とスタッフ9（募集3人含め）で40人ぐらい。

**Comment by linyows** [comment]
`100,000 / 40 = 2,500` おっっっっっ

**Comment by linyows** [comment]
決まったのでclose
