### ISSUE TITLE
サイトを完成させる

### ISSUE THREAD

**Issue by linyows** [fukuokago/event#24]
#13 から引き続き やってる

- [x] Responsive
- [x] NavBar対応
- [x] Header Design
- [x] Favicon、App Icons
    - [x] 仮で作ったもの設置済み
    - [x] 正式Icon作成
- [x] パフォーマンス向上
    - [x] PWA対応
    - [x] SSRをやめる
    - [x] GCPへ引越し（StaticIP -> LB(443, 80) -> storage）
    - [x] img圧縮まわり
    - [x] Cloud CDNを有効にする
- [x] i18n対応
    - [x] nuxt-i18n使う
    - [x] Translate to english
- [ ] 各コンテンツのimg差し込み
- [x] Background Design: Mini Gophers parallax
- [ ] トラッキングブロック対応（多分アナリティクス）

**Comment by linyows** [comment]
あとちょい

**Comment by monochromegane** [comment]
:gopher:

**Comment by linyows** [comment]
英語翻訳作業。<i18n>タグの中でyaml形式で翻訳を書く。例: https://github.com/fukuokago/fukuoka.gocon.jp/blob/master/components/About.vue

- [x] [About](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/About.vue) もう少し情報追加する
- [x] [CallForPapers](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/CallForPapers.vue) まだ募集要項できてない
- [x] [CodeOfConduct](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/CodeOfConduct.vue) これはもうこれで良さそう 報告フォームぐらいかな
- [x] [Fukuoka](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Fukuoka.vue) バッチリじゃない？
- [x] [News](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/News.vue) コンポーネント管理が微妙かも
- [x] [Registration](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Registration.vue) まだ募集要項できてない
- [x] [Schedule](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Schedule.vue) タイムテーブルはあるが未完
- [x] [Scholarships](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Scholarships.vue) 募集要項できてない
- [x] [Sponsors](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Sponsors.vue) こちらも募集前かつ募集要項作成中
- [x] [Talks](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Talks.vue) 登壇者決まってないからそれ用に何か
- [x] [Team](https://github.com/fukuokago/fukuoka.gocon.jp/tree/master/components/Team.vue) ほぼ完成

追加が必要なページ

- [x] call-for-sponsors

**Comment by linyows** [comment]
a

**Comment by linyows** [comment]
a

**Comment by linyows** [comment]
a

**Comment by linyows** [comment]
ほぼできてるので一旦仕切り直す
