### ISSUE TITLE
会場設営にひつようなもの

### ISSUE THREAD

**Issue by linyows** [fukuokago/event#25]
- プロジェクターとスクリーン 2つ
- アンプとスピーカ（BGMもならしておきたい）
- ワイヤレスマイク4つ（司会と登壇）
- 登壇者の後ろにのぼりとか撮影用に欲しい（GoConとスポンサーの）
    - メディアに連絡すると記事書いてくれるかな
- 入り口の看板的な（雰囲気出し）
- ビールサーバ
- ソフトドリンクサーバ（冷蔵庫？）
- 参加者の識別IDプレートみたいなの（これに登壇者か未成年かどうかを追加）

**Comment by monochromegane** [comment]
細かいですが，ワイヤレスマイク，一日フルだと充電持たない気がするので，予備があっても良さそうだと思いました！（もしくは充電器）

**Comment by linyows** [comment]
大事！

**Comment by linyows** [comment]
これ系、振り返りでまとめる
