### ISSUE TITLE
ランチマップ作る

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#27]
県外組が福岡良いねと言ってもらえるように美味しいお店を紹介するランチマップを作る

- [ ] Google Map上にランチマップを作る
- [ ] fukuoka.gocon.jp で参照できる

**Comment by seike460** [comment]
考慮点をまとめる

- [ ] 土日なので定休日や特別休み
- [ ] 広さ
- [ ] 夏で有る
- [ ] 福岡らしさ
- [ ] 開催場所付近
- [ ] 安くて、きれいで、うまい

**Comment by linyows** [comment]
おお、あざます！！！沢山考慮するのムズイので、うまい、開いてる、近いの3点で良さそうです！あとは、混み具合を報告出来ればいいのかなあ。いいやり方を考え中。

**Comment by linyows** [comment]
https://github.com/fukuokago/fukuoka.gocon.jp/issues/14 募集地
