### ISSUE TITLE
Fukuoka.go画像系制作物について

### ISSUE THREAD

**Issue by keitakawamoto** [fukuokago/event#4]
@linyows から依頼があり制作させていただきます。
- ロゴ
- イベント用画像

必要なものと、どんな感じがいいとか皆さんがこれはいいものだと思うものの共有などをお願いします〜。

**Comment by linyows** [comment]
キーワード的には
- Go
- 福岡
- コミュニティ
- 楽しい

かなー

**Comment by monochromegane** [comment]
@keitakawamoto ありがとう〜 :smile: 

他にキーワードあるかなあ

やっぱりGolangのマスコット [Gopher](https://www.google.co.jp/search?q=golang+gopher&safe=off&client=firefox-a&hs=9kU&rls=org.mozilla:ja-JP-mac:official&hl=ja&channel=fflb&source=lnms&tbm=isch&sa=X&ei=5CoIVKz7O8W0uASnmoDYDg&ved=0CAgQ_AUoAQ&biw=1381&bih=715) は前面に出さないにしても、少しあったほうが見る人がGolangのコミュニティだってわかりやすいのかな。

デザインしにくいかｗ

**Comment by keitakawamoto** [comment]
Gopher要素は必要でしょうね。。。
考えてみますー。

逆に福岡要素が迷いますね。
`F`でしょうか。

**Comment by linyows** [comment]
Fじゃ伝わりにくいので、ランドマークとか

**Comment by keitakawamoto** [comment]
http://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%B3%E3%83%89%E3%83%9E%E3%83%BC%E3%82%AF

福岡は福岡タワーらしいですな。

**Comment by monochromegane** [comment]
福岡タワー、関東のひとに知名度まったくなかった
へーそんなのあるんですね、みたいな:sweat_smile:

**Comment by keitakawamoto** [comment]
アカン...
関東人から見た福岡とは？:finnadie:

**Comment by keitakawamoto** [comment]
`#dev` で関東の方にお訪ねした結果
- ラーメン
- 手榴弾
- ロケットランチャー
- モツ鍋
- 明太子
- 山笠

プラチナミッキーの言う通り、福岡タワー、認知されていなかったw

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/4436265/721fca3e-476f-11e4-8c99-574b45f7b382.png)

@linyows  @monochromegane 

まだ微調整やフォント選びがまだですが、下の丸いやつで行こうかと思ってます。
こんな感じでどうでしょうか。

**Comment by linyows** [comment]
おお、いいすね〜 色の組み合わせが良い

**Comment by linyows** [comment]
明太子感だすのむずいね...

**Comment by linyows** [comment]
~~どうせなら、角帽を笠にしてみるとか~~ うーん微妙か。でも何かアカデミックっぽい雰囲気が強いなあ

**Comment by keitakawamoto** [comment]
よかった！
山笠の笠って、どんなやつでしたっけ...（画像検索しても笠被ってる人見当たらず）

明太子感、リアルにぶつぶつを検討したのですが、気持ち悪い上に縮小したら視認できないので、やめました:finnadie:

**Comment by linyows** [comment]
山笠は神輿の事っぽいので笠関係ないす...

**Comment by linyows** [comment]
大学っぽいのをどうにかしたくて。

**Comment by linyows** [comment]
頭にラーメン乗せるのはどうだろう

**Comment by keitakawamoto** [comment]
> 山笠は神輿の事っぽいので笠関係ないす...

うう、無知でした...

> 大学っぽいのをどうにかしたくて。

なるほど。勉強感を出したかったのですが、逆効果でしたか...
では大学っぽくなく、福岡名産っぽいのを！ラーメンやってみますね。

**Comment by keitakawamoto** [comment]
@linyows 
方向性の共有のため、雑ですが画像を用意しました。
ラーメン置いてみました。（あとでラーメンの精度上げと影をつけます）

![image](https://cloud.githubusercontent.com/assets/1661325/4453544/daaa08fe-485e-11e4-868e-5889150a3c5f.png)

**Comment by linyows** [comment]
いいね〜 話してて出たアイデア
- 博多にわかの面をつける
- ラーメンっぽい具をドンブリからみ出してみる

**Comment by linyows** [comment]
○からラーメン出ないようにゴーファーやや下げてみたらどうかな

**Comment by keitakawamoto** [comment]
@linyows 
できました〜。
ラーメンとにわか面の２種類作りました！
（ひとつにまとめるとごちゃごちゃしすぎるので）
どっちかに絞らず、場合によって使い分けるとかしてもいいかも...とちょっと思いました。

### アイコン

![fukuokagoicon1](https://cloud.githubusercontent.com/assets/1661325/4519798/d7ce0d3a-4ccb-11e4-871b-14b2dae1cdf9.png)
![fukuokagoicon2](https://cloud.githubusercontent.com/assets/1661325/4519800/dafe3d5e-4ccb-11e4-8658-eafe8ff77a3d.png)

### テキスト

![fukuokagotitle1](https://cloud.githubusercontent.com/assets/1661325/4519804/ed0e516e-4ccb-11e4-8d89-0c60a1a81938.png)
![fukuokagotitle2](https://cloud.githubusercontent.com/assets/1661325/4519805/f15a2b3a-4ccb-11e4-85e2-71ebc14b5c37.png)

> ○からラーメン出ないようにゴーファーやや下げてみたらどうかな

ラーメンタイプはGopherを下げて、ラーメンをおさめました。箸とわかるよう、箸の一部は削らず飛び出しています。

コミュニティ名のテキスト画像は、黒文字・白文字の２種用意しました。

**Comment by linyows** [comment]
@keitakawamoto いい感じ〜 :+1:、ラーメンとにわか２種類にわけるのいいね。ただにわかの分がちょっと輪郭がぼやける感じがあるのでGopherの青より濃い色はどうでしょうか。黒に近いグレーででシャドーを黒にするとか、Goは小文字がいいかなー

**Comment by keitakawamoto** [comment]
@linyows お、了解す。

> にわかの分がちょっと輪郭がぼやける感じがあるのでGopherの青より濃い色はどうでしょうか。

これはにわかが周りの色に埋もれずちゃんと輪郭がくっきり見えると良いってことですね。調整してみます！

`Go -> go`も了解です〜。あの大文字の`G`の丸さに惚れちゃいまして大文字にしてしまいましたw

**Comment by keitakawamoto** [comment]
### メモ

背景色と面の色が近いため面の輪郭を視認しにくい。
背景色のいろいろなバリエーションを用意して検討する。

**Comment by miyakey** [comment]
:+1::+1::+1:

**Comment by linyows** [comment]
@keitakawamoto @miyakey サイトのたたき台です http://fukuokago.github.io/

**Comment by keitakawamoto** [comment]
おおー:heart_eyes:

**Comment by miyakey** [comment]
:metal:

**Comment by keitakawamoto** [comment]
@linyows @monochromegane 

小文字の`.go`の用意できました。

![ed0e516e-4ccb-11e4-8d89-0c60a1a81938_2](https://cloud.githubusercontent.com/assets/1661325/4535692/f9592578-4db8-11e4-8d75-0fca5150137f.png)
![ed0e516e-4ccb-11e4-8d89-0c60a1a81938](https://cloud.githubusercontent.com/assets/1661325/4535693/f97ddaf8-4db8-11e4-845d-47744ae5ad14.png)

にわか面タイプの画像のカラーバリエーションをいくつか用意してみました。
どうでしょう？

![image](https://cloud.githubusercontent.com/assets/1661325/4535724/8d0c6e88-4db9-11e4-8290-2cbe3d61c4dd.png)

**Comment by linyows** [comment]
@keitakawamoto :+1:  青かなあ〜

**Comment by linyows** [comment]
バナーもあると助かるー 970×250とか

**Comment by keitakawamoto** [comment]
@linyows 

でかいpng用意しました。

![-1](https://cloud.githubusercontent.com/assets/1661325/4537524/7bd262f6-4dde-11e4-81c8-d4136e660cf4.png)

**Comment by keitakawamoto** [comment]
> バナーもあると助かるー 970×250とか

お、connpassに使えたりするバナーですか？

**Comment by linyows** [comment]
@keitakawamoto ありがとう〜、そすそす

**Comment by keitakawamoto** [comment]
ではいくつか試作品を用意しましょう。
少々お待ちを。

**Comment by monochromegane** [comment]
Fukuoka.go#4のイベントページで使わせてもらいました！:metal: 
やっぱ画像あると違うね！ ありがとう！！

**Comment by keitakawamoto** [comment]
@monochromegane 
いえいえ〜気に入ってもらえてよかった :laughing:

@linyows 
方向性、こんな感じかなーというのをいくつか用意しました。

![2014-10-16 8 26 52](https://cloud.githubusercontent.com/assets/1661325/4655379/c83ef88a-54c2-11e4-82e0-dd00f7158a11.png)

埋め込み
![2014-10-15 22 34 53](https://cloud.githubusercontent.com/assets/1661325/4655351/58a20c92-54c2-11e4-9ad9-85cfa5cdcfca.png)
![2014-10-15 22 23 09](https://cloud.githubusercontent.com/assets/1661325/4655355/5ca8356e-54c2-11e4-9f62-32df03499e09.png)
![2014-10-15 22 37 42](https://cloud.githubusercontent.com/assets/1661325/4655357/5e7d7e80-54c2-11e4-9c90-60b956db1f3f.png)
![2014-10-16 8 25 56](https://cloud.githubusercontent.com/assets/1661325/4655377/baaafe1c-54c2-11e4-8dbd-82971062b781.png)
![image](https://cloud.githubusercontent.com/assets/1661325/4655442/bf62fe04-54c3-11e4-984a-370e64f4631f.png)
![image](https://cloud.githubusercontent.com/assets/1661325/4655444/c8d51d96-54c3-11e4-90d1-253e6fd828de.png)

**Comment by keitakawamoto** [comment]
イメージしているものがあれば、是非共有を〜

**Comment by linyows** [comment]
おっと、ごめん。えーと、アイコンが被ってるのでうーむとなっていたでござる。背景にでかいラーメン配置して前にちっさくgopherとかでいいようなとか考えていた。ラーメンのどんぶりにFukuoka.goと書いてあるとか。

**Comment by keitakawamoto** [comment]
被りについては、他のコミュニティも被っていたので、アリかなーと思って作っちゃいました。
確かに理想的にはないほうが。

> 背景にでかいラーメン配置して前にちっさくgopherとかでいいようなとか考えていた。ラーメンのどんぶりにFukuoka.goと書いてあるとか。

ありがたや！用意してみます〜

**Comment by keitakawamoto** [comment]
@linyows ラーメンは実写とイラストどちらがいいですか？

**Comment by linyows** [comment]
あ、今あるイラストを拡大でいいと思う。

**Comment by keitakawamoto** [comment]
了解です〜

**Comment by keitakawamoto** [comment]
@linyows バナーできました〜。どうでしょう？
（gopher、グループ画像で横にいるしいいかなって思って入れませんでした...）

![fukuokago_banner_03](https://cloud.githubusercontent.com/assets/1661325/4763705/c5da7980-5b15-11e4-9e97-c84f34ba84eb.png)

![image](https://cloud.githubusercontent.com/assets/1661325/4763700/ba46716e-5b15-11e4-9210-d6877c371ca9.png)

**Comment by linyows** [comment]
> gopher、グループ画像で横にいるしいいかなって思って入れませんでした...

あーでも、ラーメンのコミュニティっぽいかも

**Comment by keitakawamoto** [comment]
ではいれたバージョンを用意しましょう。

**Comment by keitakawamoto** [comment]
@linyows 

すみません、いろいろあり遅くなってしまいました:bow:
以下のようなgopherの挿入、どうでしょうか。

![image](https://cloud.githubusercontent.com/assets/1661325/4895010/6dbb9716-63df-11e4-96fa-bfead4d8676d.png)

視線をラーメンではなくロゴにしたVer
![image](https://cloud.githubusercontent.com/assets/1661325/4895032/ec0c6fe6-63df-11e4-9004-50eb0467c256.png)

ちっちゃいVer
![image](https://cloud.githubusercontent.com/assets/1661325/4895014/7d0be66c-63df-11e4-8064-61e8b137fcfd.png)

**Comment by miyakey** [comment]
:+1: 
一番上がいいなと思いました〜

**Comment by keitakawamoto** [comment]
@miyakey  970×250用意しました。
サイズ調整や微調整などはいつでもやるので、気軽にお声かけください〜

![fukuokago_banner_03](https://cloud.githubusercontent.com/assets/1661325/4990723/ac20cf18-69ce-11e4-922a-57b1356db98c.png)

**Comment by keitakawamoto** [comment]
@linyows にも確認をしたので、close
