### ISSUE TITLE
Tシャツできました

### ISSUE THREAD

**Issue by keitakawamoto** [fukuokago/event#6]
@linyows @monochromegane 

お待たせしました。忘れてました:finnadie:
Tシャツができましたので共有します〜。
シャツの内容・説明文等の修正、リクエストがあればこちらにお願いします。
- https://suzuri.jp/keita_kawamoto/omoide/2234

![image](https://cloud.githubusercontent.com/assets/1661325/8963965/f0d85be2-365d-11e5-976b-675ec1845603.png)

**Comment by linyows** [comment]
ほほ〜、買った

**Comment by keitakawamoto** [comment]
:sushi: 
では何かリクエストがあれば再openということで、closeしますー
