### ISSUE TITLE
ステッカーを作る

### ISSUE THREAD

**Issue by linyows** [fukuokago/event#7]
そろそろ、ステッカーを作ってもいいのかなって思っていて、シンプルなsuzuriのやつもいいけど、できればmacに貼ってもらえるやつもいいかなあと思っている。

こういうの。
http://thedecalguru.com/macbook-decals/

@keitakawamoto 大先生にアイデア聞いてみようかな

**Comment by keitakawamoto** [comment]
おっ。どんどん勢力を増していますね、fukuoka.go! Twitterトレンド入りまでしてポケモンGO勢を困惑させるレベルですね。最高です。

いろいろなステッカーバリエーションのスケッチを用意してみますので、気長にお待ちください〜

## 参考：現在のステッカー

記録としてissueに残しておく。

> シンプルなsuzuriのやつ

はコレ。https://suzuri.jp/keita_kawamoto/725888/sticker/m/white

![image](https://user-images.githubusercontent.com/1661325/41635104-de03b18c-7481-11e8-8bc8-f4150c7796b2.png)

**Comment by keitakawamoto** [comment]
![image](https://user-images.githubusercontent.com/1661325/41635445-b4ee6b82-7483-11e8-82a2-458719bfd916.png)

こういうのどうやって発注するんだろ

**Comment by linyows** [comment]
@k1low さんが作ってたので聞いたら以下の業者で注文したらしい

https://www.quackworks.jp/

ただ、転写シートが白色なのでアップルマークに合わせるのが大変だったとのこと。ここが透明なものを取り扱っている業者を探す方が良いかも

**Comment by linyows** [comment]
アイデア

- にわかの面つけたgopherがリンゴかじる [こんなん](https://www.amazon.co.jp/%E3%82%AF%E3%83%83%E3%82%AD%E3%83%BC%E3%83%A2%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%BC-Cookie-Monster-Macbook-13%E3%82%A4%E3%83%B3%E3%83%81%E5%AF%BE%E5%BF%9C-%E3%82%B9%E3%83%86%E3%83%83%E3%82%AB%E3%83%BC-C78-%E4%B8%A6%E8%A1%8C%E8%BC%B8%E5%85%A5%E5%93%81/dp/B06XQCJWK3/ref=sr_1_29?m=A2YFB57EVDND0H&s=computers&ie=UTF8&qid=1530773764&sr=1-29&refinements=p_6%3AA2YFB57EVDND0H)
- リンゴににわか面をつけるgopher

**Comment by keitakawamoto** [comment]
なるほど！
きになるところは、最新のMBPは発行せずメタリックな感じになってますが、ステッカーと合うでしょうか？いい感じになるかな〜試したいw

**Comment by linyows** [comment]
@keitakawamoto おやまさんのマシンを見せてもらったらイメージ湧くかもしれないす

**Comment by keitakawamoto** [comment]
お！ちょっと覗きに行きまっす！

**Comment by keitakawamoto** [comment]
## 光らないメタリックなものとも合いそう

というかクールそう。いくつか案を作ってみまっす！

以下おやまさんのマシン
![image](https://user-images.githubusercontent.com/1661325/42549852-4e2c914e-8509-11e8-9e1f-102e3e0cbecd.png)

**Comment by linyows** [comment]
汎用的なステッカーもあったほうがいいので以下で注文しようかな。耐久いいやつとしてPVC（塩ビ）+ラミネートで、500枚と1000枚で1000円しか変わらないので1000枚で...
http://www.adprint.jp/

![180719-0001](https://user-images.githubusercontent.com/72049/42918184-aff9515c-8b47-11e8-8c78-c876023c9426.png)

ちなみにsuzuriで100枚注文すると¥42,188...

**Comment by linyows** [comment]
4色じゃ厳しいのか

**Comment by monochromegane** [comment]
golang.tokyoのステッカーはかわいかったなあ

**Comment by linyows** [comment]
新しいfukuoka gopherを河本くんが作ってるので仕切り直し

**Comment by keitakawamoto** [comment]
RubyKaigi2019のステッカー作りを担当しているのですが、

- https://www.stickermule.com/jp/products/die-cut-stickers

ステッカーミュールでやります。Fukuoka.goもここで生産するのはどうでしょうか（仕切り直し後）

**Comment by keitakawamoto** [comment]
俺のブログのロゴも刷っちゃお〜〜〜〜
