### ISSUE TITLE
Fukuoka.go#13はOkayama.goと一緒にやりたい

### ISSUE THREAD

**Issue by monochromegane** [fukuokago/event#9]
ref: https://twitter.com/monochromegane/status/1067258144995201024

**Comment by monochromegane** [comment]
とりあえず一度現状把握して方向性を合わせると良いと思うので確認したい事項をリストアップしてみる．追記などあれば自由にお願いします．

## Agenda

- [x] 目的の設定（トークを聞いてもらいたいのか交流が目的か）
- [x] 日程調整
- [x] 福岡側の場所確保
- [x] 岡山側の場所確保(要: インターネット，カメラ，プロジェクタ)
- [ ] イベント内容
  - [x] トーク単方向or双方向
  - [ ] 懇親会のリモートでの相互交流をどうするか
- [x] スポンサー（Forkwellさんのスポンサーを岡山まで広げることは可能か）
- [x] 告知方法（Connpassを別ページにするのか）
- [x] 継続について
- [x] 岡山と画面共有しながらの発表を事前リハーサルする

**Comment by linyows** [comment]
Oyama.goに空目... あざmす！

**Comment by linyows** [comment]
交流が目的なんだけど手段がトークなのかなあと思いました。前半と後半分けて、コミュニティ双方で発表を行うのはどうでしょう。Okayama.goの普段がどういう雰囲気か知りたいところです。懇親会は、リモート越しにやるのは敷居が高い気はしました。個別に行うが現実的かなあー

**Comment by monochromegane** [comment]
なるほどなるほど〜．Okayama.goは実はまだなくて参加人数なども未知数って感じみたいです．
やはり一度ざっくばらんに相互の現状を伝え合うMTGを設けましょうかね〜

**Comment by monochromegane** [comment]
いわたプロのGitHubアカウントがわからない...!!

### 状況の共有

1. トークについて
    岡山会場からは，今の所，1名分(いわたプロ)のトークを想定しようかなと思っています．もちろんトーク希望があれば枠はできるだけ確保します．

2. 日程について
   2019/02の上旬ぐらいにできればなあと考えています．

### 質問

1. 中継設備を伴う場所の確保について
    今回の中継にあたり，Google {Hangout, Meet}を想定してます．岡山会場で以下の設備がある会場って抑えることはできそうでしょうか
    - インターネット環境 (必須)
    - プロジェクタ，スクリーン (できれば)
    - スピーカーマイク (できれば)

2. 食事の準備について
    Fukuoka.goでは食事とお酒を提供しています．また最初の15分をネットワーキングタイムとしてスポンサー動画を見ながら食事や挨拶を行います．
    岡山会場で食事有無でこの辺を同期するか決めないとなと思ってます．
    また，Forkwellさんのスポンサーがつけば参加人数xビール一本分程度なら確保できます．この辺はForkwellさんとお話が必要になりそう．

**Comment by qt-luigi** [comment]
monochromegane さん、改めましてこの度はお誘いありがとうGoざいます！q@w@p
linyows さん、初めましてというかなんというか私はGoCon 2017 Springにて発表を拝聴させて頂いておりました！m(__)m

一先ず、自己紹介がてら岡山のGoイベントの状況をば。

現在、私が知っている岡山のGoイベントは以下の通りで、私は一通りお手伝いをさせて頂いております。

- GDG中国さん主催の「Golang Cafe」の開催（現在までに82回開催されています！去年、開催権限を頂きましたが2月を最後にちょっとできてません...）https://gdgchugoku.connpass.com/
- 小西さんという方が主催の「岡山システムプログラミング勉強会」で書籍「Goならわかるシステムプログラミング」の本読み会（小西さんと私とあと広島から1名参加で3名で月1〜2回ペースでやってます）https://okasyspro.connpass.com/
- 山下さんという方＆GDG四国さんが主催の「香川Go言語勉強会」で今は入門ハンズオン＆講師（2ヶ月に1回のペースで開催＆次回は1/12）https://gdgshikoku.connpass.com/

あとは私が個人で毎年2月と8月に「Go Release Party」を主催しています。
いずれのイベントも参加者は1桁台という状況です。

今回、お話を頂いて私が主催できる「Okayama.go」を立ち上げました。（Go Release Partyはこちらに含めました）https://okayamago.connpass.com/
ちなみに、名前は本スレッドで初めて登場したので名付け親はmonochromeganeさんですw

**Comment by qt-luigi** [comment]
2019年2月開催なら「Go 1.12 Release Party in 福岡 or 岡山」にするのもアリかも!? q@w@p
ちなみにGo Release Partyですが日本では毎回東京、静岡、岡山が開催しています。
Go参考までにの発言のため今まで通り*.goとpartyと別々イベント開催で勿論大丈夫です！（岡山は別々でもやりますよぉ〜）

**Comment by linyows** [comment]
@qt-luigi 初めまして！そしてよろしくお願いします！

**Comment by qt-luigi** [comment]
基本的にはFukuoka.goさん主導で決定して頂いてこちらが追随する形で大丈夫です。

トーク

岡山での各Goイベント開催感からすると私以外は少し難しいかもしれませんが、せっかくなのでこちらでも若干名募集してみます。

日程

そちらに合わせます。これまでの流れですと平日の19時スタートですよね。

会場

岡山はネットが使える施設が少ないので探す必要があります。日程が決まれば相手と話がしやすいかもしれません。最悪は私のWi-Fiルーター＆MacBookAirの画面＆カメラ＆マイクで対応します。通信手段(?)は私もGoogle{Hangout, Meet}ぐらいしか知らないので助かります。

食事

そちらのタイムテーブルに合わます（そちらが食事タイムならこちらでも何か食べる感じで）。スポンサーさんもそちらにお任せします。準備ややりとりが煩雑になるようでしたらこちらはなしで大丈夫です。例えばGolang Cafeですと各自で注文して食べ飲みしながらやってたりしています。

**Comment by monochromegane** [comment]
@qt-luigi 情報ありがとうございます！まずは日程を決めてみます~!!

**Comment by linyows** [comment]
イベントページ(connpass)はどうしましょうかねー それぞれで行うのがシンプルでいいかな

**Comment by monochromegane** [comment]
そうですね，会場も違うことですし，混乱しないよう分けた方が良い気がしてきました．
相互リンク（懐かしい！！）を貼りましょう〜

**Comment by monochromegane** [comment]
@qt-luigi `2/12` で進めようと考えています〜．現時点で岡山側で難しい日程でないかだけ確認お願いします！

**Comment by qt-luigi** [comment]
岡山側2/12(火)で大丈夫です＆connpass分け分け了解です！q@w@p

**Comment by monochromegane** [comment]
@qt-luigi 申し込みページはこんな感じにする予定です．
ひとまずOkayama.go枠で Talk(15min),LT(5min)をそれぞれ一枠づつ確保しています！
見えますかね？
https://fukuokago.connpass.com/event/112073/preview/

**Comment by qt-luigi** [comment]
枠確保ありがとうGoざいます！q@w@p URLですがconnpassにログインしても見れませんでした。

**Comment by monochromegane** [comment]
う，すみません，こんな感じです！

```
# Fukuoka.goとは

福岡でGo言語やりたい！やってる！人が集まって情報交換したり、もくもくしたりするコミュニティです！だんだんとプロダクション環境でも利用されてきたGo言語。やったことある人も、そうでない人も、Fukuoka.goで集まって情報交換しましょう〜。

# イベント概要

Fukuoka.go#13、今回もトーク大会です！Goの活用事例を持ち寄って福岡Go言語の"今"を感じましょう。当日は懇親会も予定しています。常連の方も久々の方も初めての方も、わいわい楽しくおしゃべりしましょう！
さらに，今回は岡山のGo言語コミュニティである[Okayama.go](https://okayamago.connpass.com/)との中継もあります！今まで以上にGoの繋がりを広げてみませんか〜？

# 日時と場所

2019/02/12（火）

時間 | 内容
--- | ---
18:45 | 開場
19:00 | 乾杯/ネットワーキング
19:15 | 美味しいご飯とお酒を肴に楽しい発表を聞く
21:45 | 懇親会
22:10 | 終了

※懇親会は無料です。

会場：ペパステ
福岡県福岡市中央区天神2丁目7番21号 天神プライム 7F
GMOペパボ株式会社（福岡支社）

### 発表

<p style="color:red">発表者募集中です。Talk(15分) or LT(5分)</p>

時間 | タイトル | スピーカー
--- | --- | ----
19:15 | Talk1:   | @monochromegane
19:30 | LT1:  | -
19:35 | 質問バッファ |
19:45 | Talk2:   | Okayama.go枠 (@qt-luigi)
20:00 | LT2:  | -
20:05 | 質問バッファ |
20:15 | Talk3:  | -
20:30 | 質問バッファ |
20:40 | 休憩 |
20:50 | Talk4:  | -
21:05 | LT3:   | Okayama.go枠(仮)
21:10 | 質問バッファ |
21:20 | Talk5:  | -
21:35 | LT4:  | -
21:40 | LT5:  | -
21:45 | 質問バッファ |

# ディスカッション

Fukuoka.goのスラックチームです。お気軽にどうぞ！

Slack Team: <a href="https://slack.fukuokago.tech">https://slack.fukuokago.tech</a>

# 発表者

### [@monochromegane](https://twitter.com/monochromegane)

<img src="https://d19ta9rijs3cxg.cloudfront.net/wp-content/uploads/sites/2/2017/05/13692462_1013755355398990_5321412467621857881_n-e1494916040772.jpg" width="100">

ペパボ研究所 研究員、GMOペパボ プリンシパルエンジニア。Golang/Ruby/機械学習 | Photo: モノクロがメイン。渡部さとるWS2B 14期参加 | Music: エレファントカシマシ | Sports: 柔道

### [@linyows](https://twitter.com/linyows)

<img src="https://d19ta9rijs3cxg.cloudfront.net/wp-content/uploads/sites/2/2017/05/18034339_10155301355289047_5275350369800289733_n-e1495099710161.jpg" width="100">

GMOペパボ技術基盤チーム・プリンシパル。整備技術と開発力でGMOペパボ技術基盤チームを支えるエンジニア。capistrano-github-release, octopassなど無数の、現場の問題を解決するOSSの作者でもある。

### 大谷祐司

<img src="https://www.wingarc.com/product/motionboard/iot/iot-juku/img/img_fukuoka06.jpg" width="100">

株式会社サーキュレーション CTO。サイバーエージェントでインターネット広告のシステム部門を立ち上げ、子会社の技術責任者に就任。 その後インテリジェンスで技術責任者としてエンジニア組織を立ち上げる。 2017年1月より福岡に移住し、スタートアップCTOを経てサーキュレーションに参画。

# 注意事項

- 飲食のみを目的としたご応募・ご来場はご遠慮ください。
- 補欠者の方はご来場いただいても、ご入場いただくことができませんのでご了承ください。
- キャンセルされる場合はイベントの3日前までにお願いいたします。

# 過去イベント

- [GoConference 2014 spring](http://connpass.com/event/6370/)
- [GoCon福岡二次会](http://connpass.com/event/6716/)
- [Fukuoka.go#1](http://connpass.com/event/6887/)
- [Fukuoka.go#2](http://connpass.com/event/7559/)
- [Fukuoka.go#3](http://fukuokago.doorkeeper.jp/events/14905)
- [Fukuoka.go#4](http://fukuokago.doorkeeper.jp/events/16289)
- [Fukuoka.go#5](http://fukuokago.doorkeeper.jp/events/17415)
- [Go Conference 2014 autumn](http://gocon.connpass.com/event/9748/)
- [Fukuoka.go#6](https://fukuokago.doorkeeper.jp/events/18312)
- [Fukuoka.go#7](https://fukuokago.doorkeeper.jp/events/23212)
- [Fukuoka.go#8](https://connpass.com/event/55098/)
- [Fukuoka.go#9](https://connpass.com/event/68358/)
- [Fukuoka.go#10](https://fukuokago.connpass.com/event/81056/)
- [Fukuoka.go#11](https://connpass.com/event/87684/)
- [Fukuoka.go#12](https://fukuokago.connpass.com/event/99807/)
```

**Comment by monochromegane** [comment]
イベントタイトルは `Fukuoka.go#13+Okayama.go` としています！

**Comment by qt-luigi** [comment]
内容＆タイトル、了解しました！
こちらも追っかけでイベントぺージを作成＆公開しますので先に公開して頂いて大丈夫です！(場所は追々で更新します)
イベントページ作成時にそちらの内容をある程度コピらせて頂きますことをGo了承くださいm(_ _)m

**Comment by monochromegane** [comment]
はい！よろしくお願いします〜
公開したらまたご連絡いたします！

**Comment by monochromegane** [comment]
早すぎてまだ飲食代に関する会社りん議も通してなかったので一旦公開待ちw

**Comment by monochromegane** [comment]
OKいただいたので，公開しました！
https://fukuokago.connpass.com/event/112073/

**Comment by linyows** [comment]
わーい

**Comment by qt-luigi** [comment]
わーい！q@w@p

**Comment by monochromegane** [comment]
TODOに `岡山と画面共有しながらの発表を事前リハーサルする` を追加しました．
岡山側の会場など決まったら，どこかで日程決めてやりましょう〜 @qt-luigi

**Comment by qt-luigi** [comment]
リハ了解しました、が、会場を検討中でして、もうしばらく時間をかけさせてくださいm(__)m
あと私はネットをしにくい職場のため日中はレスポンスが鈍くなることをGo了承くださいm(__)m

**Comment by monochromegane** [comment]
おお，承知しました！急ぎませんので決まりましたらご連絡ください〜（Fukuoka.goは楽しくサステナブルがモットーです）

**Comment by qt-luigi** [comment]
会場決まりました！q@w@p 今connpass作成中なのですがちょりっと質問？相談？させてください。
福岡の方はガンガン発表がされていく流れですが、ネットで繋げられるのはネットワーキングの時とかこちらの発表の時だけでしょうか？
そちらの発表が随時中継されるなら岡山でもそれを眺める感じで、こちらの時だけ繋がるならその間はこちらも何か（こちらはこちらで発表とかGoの座談会やら）用意しないと行けないかなぁと思っています。

**Comment by monochromegane** [comment]
会場選定ありがとうございます〜！ & お疲れ様です！

中継について常時接続で考えています．
こちらの発表の時は岡山側で聞いてもらって，岡山側の発表の時は，こちらはその発表を聞きます．

ですので，

> そちらの発表が随時中継されるなら岡山でもそれを眺める感じ

この感じでよさそうです！

Google meetで福岡会場，岡山会場が参加して発表者が都度そこにジョインを行う予定です〜
ここについては事前リハーサルでやりやすい接続方式を検討しませう．

**Comment by qt-luigi** [comment]
中継の常時接続の予定であること、了解しました！
そちらが発表の時は中継を見させて頂きつつ、こちらは食べたり話たりする流れにしておきます。

今回、会場は別の会社さんの施設を利用させて頂くため、実際の実現性などはリハーサル時に色々と確認させて頂けれたらと思います（よーするに「やってみにゃーわからん」です:^^;）

あと、こちら側のイベントサイトのタイトルですが「Fukuoka.go#13+Okayama.go in Okayama」で考えていますが大丈夫でしょうか？

**Comment by monochromegane** [comment]
はい〜．こちらも発表見ながら飲食する感じです！

中継はうちも初めてなのでリハーサルでやっていきましょう〜

イベント名ですが，ご提案の奴でもOKです〜．
ただ，せっかく岡山のコミュニティが立ち上がったことですから， Okayama.go#1+Fukuoka.go みたいに，岡山のGoのイベントでFukuoka.goとなんかやるよ〜みたいな感じを出していただいてもいいかな〜と思ってます

**Comment by qt-luigi** [comment]
タイトル案、ありがとうGoざいます！

そうですね、せっかく立ち上げたのだから「Okayama.go#1+Fukuoka.go」の方が良いですよね＆そうさせて頂きます！m(_ _)m

**Comment by monochromegane** [comment]
わーい！

**Comment by qt-luigi** [comment]
わーい！q@w@p

**Comment by hayashiki** [comment]
> みなさま

いわたさんとOkayama.go運営してまいります林田ですー。（福岡出身です
私も岡山より参加いたします、当日はよろしくおねがいします！

**Comment by qt-luigi** [comment]
I just publish Okayama.go#1 !! https://okayamago.connpass.com/event/112138/

**Comment by qt-luigi** [comment]
hayashikiさん共々よろしくお願い致しますーm(__)m > Fukuoka.go
あとこちらには陶山@ほぼろさんと萩野さんという方が管理者メンバーなのでもしこちらに顔を見せた際にはよろしくお願い致しますーm(__)m > Fukuoka.go

**Comment by monochromegane** [comment]
@hayashiki 林田さん，こちらこそよろしくお願いします〜！

> 陶山@ほぼろさんと萩野さん

承知しました．岡山の力を感じます...!!

**Comment by monochromegane** [comment]
イベントページきましたね！連絡ありがとうございます！

**Comment by rhoboro** [comment]
いわたさん、林田さんと同じくOkayama.go運営してまいります陶山です 😃 
大分出身で今は広島の尾道に住んでます（どちらからもビミョーにずれてるw
一緒にわいわい盛り上げていければと思いますのでよろしくお願いします〜 💪

**Comment by monochromegane** [comment]
@rhoboro 陶山さんもよろしくお願いします〜！！ 💪 💪 
ワイワイ盛り上がっていきましょう〜

**Comment by linyows** [comment]
@hayashiki @rhoboro よろしくお願いします！！

**Comment by monochromegane** [comment]
@qt-luigi cc. @hayashiki @rhoboro あけましておめでとうございます〜．イベント，ついに来月ですね！
中継形式が初めてなので事前にリハをやりたいのですが，岡山側の会場はどんな感じでしょうか．
よければ 1/21 or 1/23 の夕方にでも接続できれば〜と思っております〜！

**Comment by qt-luigi** [comment]
あけましておめでとうGoざいます！q@w@p 現在こちらの会場さんへ日程を確認中です。

１．ちなみに夕方というのは具体的には何時ぐらいからでしょうか？こちらの会場さんの定時の時刻も確認中なのですが、例えば18:00からとかでもそちらは大丈夫でしょうか？希望する開始時刻があれば教えてください。こちらの会場さんと調整してみます。
２．確認する内容はどんなものなのでしょうか？基本的にはハングアウトの調子（音声や映像が耐えるか）でしょうかね。

**Comment by qt-luigi** [comment]
こちらの会場さんとお話しして1/23(水)、1/21(月)の優先順となりましたので、一先ず1/23(水)でお願い致しますm(__)m リハ開始可能時刻は会場さんの就業時間が18:00までのためそれ以降(18:15とか)になります。如何でしょうか？

**Comment by monochromegane** [comment]
はい！それでは 1/23(水) 18:15- でリハよろしくお願いします！

確認する内容は相互の発表内容が見聞きできることです．
具体的には
Google hangouts meetの会議IDに `岡山端末` `福岡端末` `発表者端末` がジョイン， `発表者端末` が画面共有したものが `岡山端末` と `福岡端末` (これらはおそらく会場のモニターに繋がっている) が見えること．
また，発表者の音声が `岡山端末` と `福岡端末` からIN/OUTされること
が確認事項となりそうです．
お互いの環境がまだ不明なので当日お話しながら進めれたらと思いますがざっくりはこんな感じで考えています！

**Comment by monochromegane** [comment]
@qt-luigi https://github.com/fukuokago/event/issues/9#issuecomment-452526199 1/23でリハ予定ですが，問題ないでしょうか〜 cc. @hayashiki @rhoboro

**Comment by qt-luigi** [comment]
会場さんにも再度確認がとれましたので大丈夫です！1/23のリハは私と会場提供者の方の２名で対応させて頂きます。林田さんとほぼろさんは2月の本番日に！

**Comment by linyows** [comment]
@qt-luigi  @monochromegane リハありがとうございました。念の為、福岡側の構成図を残しておきます。

![190124-0001](https://user-images.githubusercontent.com/72049/51652810-4c96f480-1fd4-11e9-91c3-4a1071db4c6d.png)

Google Meetで、福岡のChromecastと岡山で接続維持し、登壇者がMeeting Roomに参加してスライドを共有する方針。（なので、URLからどこからでも参加することが可能となる）福岡会場は、登壇者はマイクを使い、登壇者と聴衆はスピーカーから音声を聞く。

**Comment by linyows** [comment]
USB Mixerはこれ https://tascam.jp/jp/product/us-42/top

**Comment by monochromegane** [comment]
完全に理解した！

**Comment by qt-luigi** [comment]
ついに今夜！皆様よろしくお願い致します！m(_ _)m こちらは18時以降から準備開始となりますので準備出来次第、連絡しまーす！q@w@p

**Comment by monochromegane** [comment]
わーい！よろしくお願いします！！！

**Comment by monochromegane** [comment]
お疲れ様でした！！！

一応振り返りしておきます

## Keep

- 拠点繋いで楽しさ倍増．また他の地域含めて繋いで行きたい
- 拠点同士で発表できると一緒にやっている感が出るので，今後もどちらも発表できるようにしたい
- 岩田プロと小田さんのコールアンドレスポンスがウケた（質問ほんとにないですか，ないでーす）
- 意外とMeet参加->画面共有で発表のやり方でもタイムロスはなかったので，URL共有とマイクオフの手順をSlackチャンネルで通知する方式で良さそう

## Problem

- 岡山側への映像が発表者しか写していなかったので，最後に数十名いたことを知ってた．
- 音声の調整に時間がかかった

## Try

- カメラは発表者と参加者が見れるように増やす or 途中で視点を動かす
- 接続方式は前日までに通知して置いて良さそう

**Comment by linyows** [comment]
みなさん、乙ました〜

Keep
--

- 拠点繋ぎ、質疑応答含めちゃんと勉強会開催できた
- それぞれのコミュニティがパワーアップしているかのように思えた
- 事前接続テストをやっていたおかげで予定時間に開始できた
- Linuxマシンの人でもmeetにつなげればいいので接続テストが不要だった

Problem
--

- 岡山の音声はマックスだった？にもかかわらず福岡での出力が小さかった（福岡側の設定の可能性が高そう、tascamのマニュアルを読む）
- 質問が少なくてオーガナイザが質問することが幾度かあった（次の質問につながればこれでよいが、オーガナイザの質問で終わることもあった。質問に敷居が高ければtwitter経由で質問を募集しても良いかも）
- 懇親会はもろ拠点間の距離が影響してくるので勉強会を通じて交流を深めたい（岡山側の登壇数をLTでいいので増やしたい）

Try
--

- 接続テストが不要とはいえ画面共有や音声ミュートのやり方を事前に共有する必要がある
- twitterまたはslack経由質問
- 参加者からフィードバック（帰るときによかったトークにシールはるとか）

**Comment by monochromegane** [comment]
長かったIssueですが，得るものもたくさんありました．
ひとまずこのIssueは閉じます！
@qt-luigi cc. @hayashiki @rhoboro 気づいたことがあれば，このIssueにぜひお書きください〜
またつなぎましょう！！！！！

**Comment by qt-luigi** [comment]
三宅さん＆小田さん、お疲れ様でした＆お世話になりました＆ありがとうごGoざいました！q@w@p

私はKPTなるものを書いたことがないので、見様見真似で...(^^;)
私のGitHub力が低いので、見た目がプレーンでスミマセン...m(__)m

Keep
----

岡山は少人数でしたが、皆さん熱心にFukuokaの皆様の発表を拝聴しておりました。
（Goは少しだけという方には、私の方で合間に補足説明を入れておりました。）

岡山にも「質問ありますか？」と振って頂いたおかげで、ちゃんと一体感が出ていました。
（肝心の質問が出せずスミマセン。Goは少しだけという方が多かったです。）

こちらはアットホームな感じで、参加者からは「楽しめました」との感想を頂けました！

Problem
-------

発表者（私）が発表するまでに、もたついてしまった。
（リハをしていたにも関わらず...スミマセン）

平日の夜のイベントということで参加者が集まりづらい。
（もともと岡山はGopherが少ないというのもありますが...）

Try
---

Okayama.goは立ち上がったばかりなので、引き続き色々やって行きで。
（Goハンズオンとか、もくもく会とか、発表できるGopherを発掘したりとか、etc.）

-----

感謝ありがとう！大成功だったかと！機会があればまた！q@w@p

**Comment by qt-luigi** [comment]
あ、ちゃんと太字になって線も引かれた。
